### ISSUE TITLE
Warning messages connecting to shadow-cljs build

### ISSUE THREAD

**Issue by jc776** [mauricioszabo/atom-chlorine#127]
With a running shadow-cljs server + build, I'm able to "Connect Socket Repl" & immediately eval in JVM Clojure (thanks, that's really great!) but I'm getting a few odd messages when I then try to connect to the browser CLJS.
1. If I try to eval CLJS before connecting, it suggests `You can connect a repl using 'Connect ClojureScript Socket REPL' command, or 'Connect a self-hosted ClojureScript'` - Neither of these two commands show up in Ctrl+Shift+P bar, but there is `Chlorine: Connect Embedded`
2. If I run that one, multiple warnings show in the Chlorine REPL window as it first connects - I do not have Reagent in any project file, what is calling these?
```
------ WARNING - :undeclared-ns ------------------------------------------------
 Resource: :27:3
 No such namespace: reagent.ratom, could not locate reagent/ratom.cljs, reagent/ratom.cljc, or JavaScript source providing "reagent.ratom"
------ WARNING - :undeclared-var -----------------------------------------------
 Resource: :27:3
 Use of undeclared Var reagent.ratom/RAtom
------ WARNING - :undeclared-var -----------------------------------------------
 Resource: :32:3
 Use of undeclared Var reagent.ratom/RCursor
--------------------------------------------------------------------------------
```
3. After those warnings, I can eval CLJS e.g. `(js/alert "Hello")` entirely fine.
4. In a CLJS file, a `nil` line shows up in the REPL for each character I type that starts to autocomplete eg `(str/` `(js/` or `(desktop`. The actual autocomplete results seems OK.
```
desktop.devcards=> nil
desktop.devcards=> nil
desktop.devcards=> nil
desktop.devcards=> nil
desktop.devcards=> nil
desktop.day1=> nil
desktop.day1=> nil
desktop.day1=> 
```

**Comment by mauricioszabo** [comment]
Hi, thanks for reporting!

1. good catch, I'll fix the message
1. there was an experimental feature when I tried to send a "blob" of code to ClojureScript. I was implementing a fix for it and though it would be fast to do, but it wasn't and I kinda forgot :laughing: 
1. Great to know!
1. I'm trying to reproduce it but still can't. Are you working on a open-source project where I can check what's happening with the same codebase? Can you send me your autocomplete-plus configurations?

Also, can you check "Experimental Features" on the Chlorine configuration, and connect to the REPL to see if `nil` still happens on the console?

**Comment by mauricioszabo** [comment]
Fixed on 0.3.7 :)

**Comment by jc776** [comment]
I've uploaded the test project I encountered these in & steps used in: https://github.com/jc776/issue-chlorine-127

I still get the `nil` lines with or without "Enable experimental".
I have only these extra packages: chlorine 0.3.7, ink 0.11.7, lisp-paredit 0.6.0, parinfer 1.23.0.
I've listed the settings for those and autocomplete-plus in the test project 'readme'.

After updating to 0.3.7, I still get the Reagent warnings:
```
cljs.user=> ------ WARNING - :undeclared-ns ------------------------------------------------
 Resource: :26:7
 No such namespace: reagent.core, could not locate reagent/core.cljs, reagent/core.cljc, or JavaScript source providing "reagent.core"
--------------------------------------------------------------------------------
------ WARNING - :undeclared-ns ------------------------------------------------
 Resource: :28:5
 No such namespace: reagent.ratom, could not locate reagent/ratom.cljs, reagent/ratom.cljc, or JavaScript source providing "reagent.ratom"
--------------------------------------------------------------------------------
------ WARNING - :undeclared-var -----------------------------------------------
 Resource: :28:5
 Use of undeclared Var reagent.ratom/RAtom
--------------------------------------------------------------------------------
------ WARNING - :undeclared-ns ------------------------------------------------
 Resource: :28:5
 No such namespace: reagent.ratom, could not locate reagent/ratom.cljs, reagent/ratom.cljc, or JavaScript source providing "reagent.ratom"
--------------------------------------------------------------------------------
------ WARNING - :undeclared-var -----------------------------------------------
 Resource: :28:5
 Use of undeclared Var reagent.ratom/RAtom
--------------------------------------------------------------------------------
------ WARNING - :undeclared-ns ------------------------------------------------
 Resource: :33:5
 No such namespace: reagent.ratom, could not locate reagent/ratom.cljs, reagent/ratom.cljc, or JavaScript source providing "reagent.ratom"
--------------------------------------------------------------------------------
------ WARNING - :undeclared-var -----------------------------------------------
 Resource: :33:5
 Use of undeclared Var reagent.ratom/RCursor
--------------------------------------------------------------------------------
------ WARNING - :undeclared-ns ------------------------------------------------
 Resource: :33:5
 No such namespace: reagent.ratom, could not locate reagent/ratom.cljs, reagent/ratom.cljc, or JavaScript source providing "reagent.ratom"
--------------------------------------------------------------------------------
------ WARNING - :undeclared-var -----------------------------------------------
 Resource: :33:5
 Use of undeclared Var reagent.ratom/RCursor
--------------------------------------------------------------------------------
```

**Comment by mauricioszabo** [comment]
Thanks, I'll clone your repository and try to reproduce here :)

**Comment by mauricioszabo** [comment]
Will publish version 0.3.8 soon that probably solved lots of these issues. Can you test it please?

Also, I currently have no Window machine and I believe the problem with `desktop.devcards=> ` appearing on console is a windows issue. I'll try to check if this new version solves this issue too

**Comment by jc776** [comment]
0.3.8 fixes all the Reagent errors, but not the `nil` lines.

I noticed [this](https://github.com/mauricioszabo/repl-tooling/blob/a24187e30461c08cfa7aeaab73efd6fd3c36a30a/src/repl_tooling/repl_client/clojurescript.cljs#L28) case happens in cljs evals/autocompletes - the `(ns abc)` block might always be [output](https://github.com/mauricioszabo/repl-tooling/blob/a24187e30461c08cfa7aeaab73efd6fd3c36a30a/src/repl_tooling/repl_client/clojurescript.cljs#L43) below. I'm not sure what's happening in the [clojure](https://github.com/mauricioszabo/repl-tooling/blob/a24187e30461c08cfa7aeaab73efd6fd3c36a30a/src/repl_tooling/repl_client/clojure.cljs#L202) case, but the same result might be ignored.

Here are some more occurrences of `nil` CLJS lines:

When I evaluate a block in a CLJS file, I get these lines:
![image](https://user-images.githubusercontent.com/6420993/71622586-a3d31b00-2bce-11ea-8c63-89d3f01c32ca.png)

When I evaluate a block in a CLJ file, I get a single console line:
![image](https://user-images.githubusercontent.com/6420993/71622552-56ef4480-2bce-11ea-9b8b-271981265682.png)

If I type characters in a `(ns abc)` form, I get these lines:
![image](https://user-images.githubusercontent.com/6420993/71622639-17752800-2bcf-11ea-9bdd-41d69cfd6626.png)

**Comment by mauricioszabo** [comment]
I'll open a new issue with this case. I'm seeing some `nil` on ClojureScript too when I try to autocomplete after the last version of Chlorine.

I don't think the problem is the code you sent me: probably that `clojurescript.cljs` file is not being used anymore (the code I use now is https://github.com/mauricioszabo/repl-tooling/blob/master/src/repl_tooling/repl_client/clojure.cljs#L244, and I just found that I didn't add `\r` to it... sorry).

I'll try to make my windows machine work, and then I'll try to fix this issue :)
